#include "backend/wgsl.hpp"
#include "common/builtins.hpp"
#include "common/format.hpp"
#include <algorithm>
#include <unordered_map>
#include <unordered_set>

namespace backend {
namespace {

using namespace ir;

// Names WGSL reserves, plus predeclared types/functions a local could shadow.
const std::unordered_set<std::string>& reserved() {
    static const std::unordered_set<std::string> words = {
        "alias", "break", "case", "const", "const_assert", "continue", "continuing", "default",
        "diagnostic", "discard", "else", "enable", "false", "fn", "for", "if", "let", "loop",
        "override", "requires", "return", "struct", "switch", "true", "var", "while",
        "NULL", "Self", "abstract", "active", "alignas", "alignof", "as", "asm", "asm_fragment",
        "async", "attribute", "auto", "await", "become", "cast", "catch", "class", "co_await",
        "co_return", "co_yield", "coherent", "column_major", "common", "compile", "compile_fragment",
        "concept", "const_cast", "consteval", "constexpr", "constinit", "crate", "debugger",
        "decltype", "delete", "demote", "demote_to_helper", "do", "dynamic_cast", "enum", "explicit",
        "export", "extends", "extern", "external", "fallthrough", "filter", "final", "finally",
        "friend", "from", "fxgroup", "get", "goto", "groupshared", "highp", "impl", "implements",
        "import", "inline", "instanceof", "interface", "layout", "lowp", "macro", "macro_rules",
        "match", "mediump", "meta", "mod", "module", "move", "mut", "mutable", "namespace", "new",
        "nil", "noexcept", "noinline", "nointerpolation", "non_coherent", "noncoherent",
        "noperspective", "null", "nullptr", "of", "operator", "package", "packoffset", "partition",
        "pass", "patch", "pixelfragment", "precise", "precision", "premerge", "priv", "protected",
        "pub", "public", "readonly", "ref", "regardless", "register", "reinterpret_cast", "require",
        "resource", "restrict", "self", "set", "shared", "sizeof", "smooth", "snorm", "static",
        "static_assert", "static_cast", "std", "subroutine", "super", "target", "template", "this",
        "thread_local", "throw", "trait", "try", "type", "typedef", "typeid", "typename", "typeof",
        "union", "unless", "unorm", "unsafe", "unsized", "use", "using", "varying", "virtual",
        "volatile", "wgsl", "where", "with", "writeonly", "yield",
        // predeclared
        "f32", "i32", "u32", "f16", "bool", "vec2", "vec3", "vec4", "vec2f", "vec3f", "vec4f",
        "vec2i", "vec3i", "vec4i", "mat2x2f", "mat3x3f", "mat4x4f", "mat2x2", "mat3x3", "mat4x4",
        "array", "ptr", "atomic", "sampler", "select", "inverseSqrt", "atan2", "transpose",
        "determinant", "u", "Uniforms",
    };
    return words;
}

std::string wgsl_type(Type t) {
    switch (t.base) {
        case Type::Base::Bool: return "bool";
        case Type::Base::Int:  return "i32";
        case Type::Base::Void: return "void";
        default: break;
    }
    if (t.is_matrix()) return "mat" + std::to_string(t.cols) + "x" + std::to_string(t.rows) + "f";
    if (t.is_vector()) return "vec" + std::to_string(t.rows) + "f";
    return "f32";
}

enum Prec { OR = 3, AND = 4, REL = 5, ADD = 6, MUL = 7, UNARY = 8, POSTFIX = 9, PRIMARY = 10 };

struct Expr {
    std::string text;
    int prec = PRIMARY;
    std::unordered_set<int> reads;   // vars this expression reads
    // For `vecNf(s)` splats: the scalar, since WGSL's vector-scalar arithmetic
    // lets `v * s` stand in for `v * vecNf(s)`.
    std::string scalar;
    int scalar_prec = PRIMARY;
};

std::string wrap(const Expr& e, int min) { return e.prec >= min ? e.text : "(" + e.text + ")"; }

const char* LANES = "xyzw";

class Emitter {
public:
    explicit Emitter(const Module& m) : m_(m) {}

    WgslOutput run() {
        for (const auto& f : m_.functions) module_names_.insert(f.name);
        line("// Generated by fluxc — Flux shader compiler", 0);
        if (!m_.uniforms.empty()) {
            line("", 0);
            line("struct Uniforms {", 0);
            for (const auto& u : m_.uniforms)
                line("  " + uniform_field(u.name) + ": " + wgsl_type(u.type) + ",  // offset " +
                     std::to_string(u.offset), 0);
            line("}", 0);
            line("", 0);
            line("@group(0) @binding(0) var<uniform> u: Uniforms;", 0);
        }
        for (const auto& f : m_.functions) {
            line("", 0);
            function(f);
        }
        return std::move(out_);
    }

private:
    const Module& m_;
    WgslOutput out_;
    int indent_ = 0;
    int cur_line_ = 0;
    std::unordered_set<std::string> module_names_;

    // Per-function state
    const Function* fn_ = nullptr;
    std::unordered_map<int, int> uses_;
    std::unordered_map<int, std::string> names_;       // materialized values and vars
    std::unordered_set<std::string> taken_;
    struct Pending {
        Expr expr;
        int  seq;
        int  depth;
        int  remaining;     // uses left (copyable loads can be used several times)
        bool copyable;
    };
    std::unordered_map<int, Pending> pending_;
    int seq_ = 0;
    int depth_ = 0;

    void line(const std::string& s, int src) {
        out_.code += std::string(indent_ * 2, ' ') + s + "\n";
        out_.line_map.push_back(src);
    }
    void stmt(const std::string& s) { line(s, cur_line_); }

    static std::string sanitize(const std::string& base) {
        std::string s = base.empty() ? "v" : base;
        if (s.size() >= 2 && s[0] == '_' && s[1] == '_') s = "u" + s;
        if (s == "_") s = "v_";
        if (reserved().count(s)) s += "_";
        return s;
    }

    std::string uniform_field(const std::string& n) const { return sanitize(n); }

    std::string fresh_name(const std::string& hint) {
        std::string base = sanitize(hint);
        std::string n = base;
        for (int k = 1; taken_.count(n) || module_names_.count(n) || reserved().count(n); ++k)
            n = base + "_" + std::to_string(k);
        taken_.insert(n);
        return n;
    }

    // ── Value plumbing ──────────────────────────────────────────────────

    std::unordered_map<int, const Inst*> leafs_;   // Const/Uniform: always inlined

    Expr leaf_expr(const Inst& i) const {
        if (i.op == Op::Uniform)
            return {"u." + uniform_field(m_.uniforms[i.imm].name), POSTFIX, {}};
        // Const
        std::string t;
        if (i.type.is_float()) t = format_float(i.fconst);
        else if (i.type.is_bool()) t = i.iconst ? "true" : "false";
        else t = std::to_string(i.iconst);
        return {t, t[0] == '-' ? UNARY : PRIMARY, {}};
    }

    Expr operand(int id) {
        auto n = names_.find(id);
        if (n != names_.end()) return {n->second, PRIMARY, {}};
        auto l = leafs_.find(id);
        if (l != leafs_.end()) return leaf_expr(*l->second);
        auto p = pending_.find(id);
        if (p != pending_.end()) {
            Expr e = p->second.expr;
            if (!p->second.copyable || --p->second.remaining <= 0) pending_.erase(p);
            return e;
        }
        return {"/* %" + std::to_string(id) + " */ 0", PRIMARY, {}};
    }

    // A name for `id`, materializing it if it is still a pending expression.
    std::string name_of(int id) {
        if (auto n = names_.find(id); n != names_.end()) return n->second;
        if (auto l = leafs_.find(id); l != leafs_.end()) return wrap(leaf_expr(*l->second), POSTFIX);
        if (auto p = pending_.find(id); p != pending_.end()) {
            materialize(id, p->second.expr, "");
            pending_.erase(p);
            return names_[id];
        }
        return "/* %" + std::to_string(id) + " */ 0";
    }

    void materialize(int id, const Expr& e, const std::string& hint) {
        std::string n = fresh_name(hint.empty() ? "t" + std::to_string(id) : hint);
        stmt("let " + n + " = " + e.text + ";");
        names_[id] = n;
    }

    // Materialize pending expressions that read any of `vars` or are in `ids`
    // (in definition order), before a statement that would change their meaning.
    void flush(const std::unordered_set<int>& vars, const std::unordered_set<int>& ids = {}) {
        std::vector<std::pair<int, int>> order;   // seq, id
        for (auto& [id, p] : pending_) {
            bool hit = ids.count(id) > 0;
            for (int v : p.expr.reads) hit = hit || vars.count(v);
            if (hit) order.push_back({p.seq, id});
        }
        std::sort(order.begin(), order.end());
        for (auto [seq, id] : order) {
            auto it = pending_.find(id);
            if (it == pending_.end()) continue;
            Pending p = it->second;
            pending_.erase(it);
            materialize(id, p.expr, "");
        }
    }

    void define(const Inst& i, Expr e) {
        int n = uses_[i.id];
        if (n == 0) return;
        // Loads, and swizzles/extracts of already-named values, are cheap to
        // repeat, so they're inlined at every use instead of getting a `let`.
        bool copyable = i.op == Op::Load;
        if ((i.op == Op::Extract || i.op == Op::Swizzle) && (names_.count(i.args[0]) || leafs_.count(i.args[0])))
            copyable = true;
        if (i.name.empty() && (n == 1 || copyable)) {
            pending_[i.id] = {std::move(e), seq_++, depth_, n, copyable};
            return;
        }
        materialize(i.id, e, i.name);
    }

    // ── Expressions ─────────────────────────────────────────────────────

    Expr binary(const char* op, int prec, int a, int b, int lhs_min, int rhs_min, bool vec_scalar = false) {
        Expr l = operand(a), r = operand(b);
        // Only one side may become a scalar, or the result would lose its vector type.
        if (vec_scalar && !r.scalar.empty()) { r.text = r.scalar; r.prec = r.scalar_prec; }
        else if (vec_scalar && !l.scalar.empty()) { l.text = l.scalar; l.prec = l.scalar_prec; }
        Expr e{wrap(l, lhs_min) + " " + op + " " + wrap(r, rhs_min), prec, l.reads};
        e.reads.insert(r.reads.begin(), r.reads.end());
        return e;
    }

    static bool fl_vec(const Inst& i) { return i.type.is_vector() && i.type.is_float(); }

    int splat_inner_prec_ = PRIMARY;   // precedence of the last call()'s single argument

    Expr call(const std::string& f, const std::vector<int>& args) {
        Expr e{f + "(", PRIMARY, {}};
        for (size_t k = 0; k < args.size(); ++k) {
            Expr a = operand(args[k]);
            splat_inner_prec_ = a.prec;
            e.text += (k ? ", " : "") + a.text;
            e.reads.insert(a.reads.begin(), a.reads.end());
        }
        e.text += ")";
        return e;
    }

    Expr postfix(int id, const std::string& suffix) {
        Expr b = operand(id);
        return {wrap(b, POSTFIX) + suffix, POSTFIX, b.reads};
    }

    Expr value(const Inst& i) {
        switch (i.op) {
            case Op::Add: return binary("+", ADD, i.args[0], i.args[1], ADD, MUL, fl_vec(i));
            case Op::Sub: return binary("-", ADD, i.args[0], i.args[1], ADD, MUL, fl_vec(i));
            case Op::Mul: return binary("*", MUL, i.args[0], i.args[1], MUL, UNARY, fl_vec(i));
            case Op::MatMul: case Op::MatScale:
                return binary("*", MUL, i.args[0], i.args[1], MUL, UNARY);
            case Op::Div: return binary("/", MUL, i.args[0], i.args[1], MUL, UNARY, fl_vec(i));
            case Op::Rem: return binary("%", MUL, i.args[0], i.args[1], MUL, UNARY);
            case Op::Eq:  return binary("==", REL, i.args[0], i.args[1], ADD, ADD);
            case Op::Ne:  return binary("!=", REL, i.args[0], i.args[1], ADD, ADD);
            case Op::Lt:  return binary("<", REL, i.args[0], i.args[1], ADD, ADD);
            case Op::Le:  return binary("<=", REL, i.args[0], i.args[1], ADD, ADD);
            case Op::Gt:  return binary(">", REL, i.args[0], i.args[1], ADD, ADD);
            case Op::Ge:  return binary(">=", REL, i.args[0], i.args[1], ADD, ADD);
            case Op::And: {
                Expr l = operand(i.args[0]), r = operand(i.args[1]);
                Expr e{(l.prec == AND ? l.text : wrap(l, REL)) + " && " + wrap(r, REL), AND, l.reads};
                e.reads.insert(r.reads.begin(), r.reads.end());
                return e;
            }
            case Op::Or: {
                Expr l = operand(i.args[0]), r = operand(i.args[1]);
                Expr e{(l.prec == OR ? l.text : wrap(l, REL)) + " || " + wrap(r, REL), OR, l.reads};
                e.reads.insert(r.reads.begin(), r.reads.end());
                return e;
            }
            case Op::Neg: case Op::Not: {
                Expr x = operand(i.args[0]);
                std::string t = wrap(x, UNARY);
                if (t[0] == '-' || t[0] == '!') t = "(" + t + ")";
                return {(i.op == Op::Neg ? "-" : "!") + t, UNARY, x.reads};
            }
            case Op::Select: {
                // select(false_value, true_value, condition)
                return call("select", {i.args[2], i.args[1], i.args[0]});
            }
            case Op::Construct: return call(wgsl_type(i.type), i.args);
            case Op::Splat: {
                Expr e = call(wgsl_type(i.type), i.args);
                // Recover the scalar operand text (call() consumed it).
                e.scalar = e.text.substr(wgsl_type(i.type).size() + 1, e.text.size() - wgsl_type(i.type).size() - 2);
                e.scalar_prec = splat_inner_prec_;
                return e;
            }
            case Op::Convert:   return call(wgsl_type(i.type), i.args);
            case Op::Extract: {
                if (i.type.is_vector())   // a matrix column
                    return postfix(i.args[0], "[" + std::to_string(i.imm) + "]");
                return postfix(i.args[0], std::string(".") + LANES[i.imm]);
            }
            case Op::ExtractDyn: {
                Expr b = operand(i.args[0]);
                Expr k = operand(i.args[1]);
                Expr e{wrap(b, POSTFIX) + "[" + k.text + "]", POSTFIX, b.reads};
                e.reads.insert(k.reads.begin(), k.reads.end());
                return e;
            }
            case Op::Swizzle: {
                std::string s = ".";
                for (int l : i.lanes) s += LANES[l];
                return postfix(i.args[0], s);
            }
            case Op::Insert: {
                std::string base = name_of(i.args[0]);
                Expr part = operand(i.args[1]);
                bool matrix = i.type.is_matrix();
                int n = matrix ? i.type.cols : i.type.rows;
                Expr e{wgsl_type(i.type) + "(", PRIMARY, part.reads};
                for (int c = 0; c < n; ++c) {
                    std::string comp = c == i.imm ? part.text
                                     : matrix ? base + "[" + std::to_string(c) + "]"
                                              : base + "." + LANES[c];
                    e.text += (c ? ", " : "") + comp;
                }
                e.text += ")";
                return e;
            }
            case Op::Shuffle: {
                // Group runs of lanes from the same source into swizzles:
                // shuffle(a, b, [4 5 2 3]) on vec4 → vec4f(b.xy, a.zw)
                int wa = i.type.rows;   // the first source is the old value of the same type
                std::vector<std::pair<int, std::string>> runs;   // source, lanes
                for (int l : i.lanes) {
                    int src = l < wa ? 0 : 1;
                    char c = LANES[l < wa ? l : l - wa];
                    if (!runs.empty() && runs.back().first == src) runs.back().second += c;
                    else runs.push_back({src, std::string(1, c)});
                }
                Expr e{wgsl_type(i.type) + "(", PRIMARY, {}};
                for (size_t k = 0; k < runs.size(); ++k) {
                    std::string src = name_of(i.args[runs[k].first]);
                    e.text += (k ? ", " : "") + src + "." + runs[k].second;
                }
                e.text += ")";
                return e;
            }
            case Op::Builtin: {
                const BuiltinInfo& b = builtin_info(static_cast<BuiltinFn>(i.imm));
                return call(b.wgsl ? b.wgsl : b.name, i.args);
            }
            case Op::Call: return call(i.callee, i.args);
            case Op::Load: {
                Expr e{names_.at(i.args[0]), PRIMARY, {i.args[0]}};
                return e;
            }
            default:
                return {"/* " + std::string(op_name(i.op)) + " */ 0", PRIMARY, {}};
        }
    }

    // ── Statements ──────────────────────────────────────────────────────

    static void collect(const Region& r, std::unordered_set<int>& stored, std::unordered_set<int>& used) {
        for_each_inst(r, [&](const Inst& i) {
            if (i.op == Op::Store) stored.insert(i.args[0]);
            for (int a : i.args) used.insert(a);
            if (i.cond >= 0) used.insert(i.cond);
        });
    }

    // Can every value in `r` be folded into the expression for `result`?
    bool inlinable_region(const Region& r, int result, int allow_store_var, int* store_value) {
        std::unordered_map<int, int> local_uses;
        for (const auto& i : r.insts) {
            if (!i.regions.empty() || !i.name.empty()) return false;
            if (i.op == Op::Store) {
                if (store_value == nullptr || i.args[0] != allow_store_var || &i != &r.insts.back()) return false;
                *store_value = i.args[1];
                continue;
            }
            if (!is_pure(i.op) && i.op != Op::Load) return false;
            for (int a : i.args) ++local_uses[a];
        }
        if (result >= 0) ++local_uses[result];
        if (store_value && *store_value >= 0) ++local_uses[*store_value];
        for (const auto& i : r.insts)
            if (i.id >= 0 && i.op != Op::Const && i.op != Op::Uniform && uses_[i.id] != 1) return false;
        for (const auto& i : r.insts)
            if (i.id >= 0 && i.op != Op::Const && i.op != Op::Uniform && local_uses[i.id] != 1) return false;
        return true;
    }

    void region(const Region& r) {
        ++depth_;
        for (size_t k = 0; k < r.insts.size(); ++k) {
            const Inst& i = r.insts[k];
            cur_line_ = i.line;
            switch (i.op) {
                case Op::Const:
                case Op::Uniform:
                    leafs_[i.id] = &i;
                    break;
                case Op::Arg:
                    break;   // named in the signature
                case Op::Var: {
                    std::string n = fresh_name(i.name.empty() ? "v" + std::to_string(i.id) : i.name);
                    names_[i.id] = n;
                    // `var x: T; x = init;` → `var x = init;` (skipping leaf constants
                    // that only exist to be inlined).
                    size_t s = k + 1;
                    while (s < r.insts.size() && (r.insts[s].op == Op::Const || r.insts[s].op == Op::Uniform)) {
                        leafs_[r.insts[s].id] = &r.insts[s];
                        ++s;
                    }
                    if (s < r.insts.size() && r.insts[s].op == Op::Store && r.insts[s].args[0] == i.id) {
                        Expr init = operand(r.insts[s].args[1]);
                        stmt("var " + n + " = " + init.text + ";");
                        k = s;
                    } else {
                        k = s - 1;
                        stmt("var " + n + ": " + wgsl_type(i.type) + ";");
                    }
                    break;
                }
                case Op::Store: {
                    Expr v = operand(i.args[1]);
                    flush({i.args[0]});
                    const std::string& n = names_.at(i.args[0]);
                    if (v.text == n + " + 1") stmt(n + "++;");
                    else stmt(n + " = " + v.text + ";");
                    break;
                }
                case Op::If: {
                    std::unordered_set<int> stored, used;
                    collect(i.regions[0], stored, used);
                    collect(i.regions[1], stored, used);
                    flush(stored);
                    Expr c = operand(i.args[0]);
                    cur_line_ = i.line;
                    stmt("if " + c.text + " {");
                    ++indent_;
                    region(i.regions[0]);
                    --indent_;
                    if (!i.regions[1].insts.empty()) {
                        cur_line_ = i.line;
                        stmt("} else {");
                        ++indent_;
                        region(i.regions[1]);
                        --indent_;
                    }
                    cur_line_ = i.line;
                    stmt("}");
                    break;
                }
                case Op::Loop:
                    loop(i);
                    break;
                case Op::Break:    stmt("break;"); break;
                case Op::Continue: stmt("continue;"); break;
                case Op::Discard:  stmt("discard;"); break;
                case Op::Return:
                    if (i.args.empty()) stmt("return;");
                    else stmt("return " + operand(i.args[0]).text + ";");
                    break;
                default:
                    if (i.id >= 0) define(i, value(i));
                    break;
            }
        }
        // Values defined in this region go out of scope.
        for (auto it = pending_.begin(); it != pending_.end();)
            it = it->second.depth == depth_ ? pending_.erase(it) : std::next(it);
        --depth_;
    }

    void loop(const Inst& i) {
        std::unordered_set<int> stored, used;
        for (const auto& sub : i.regions) collect(sub, stored, used);
        flush(stored, used);

        int update_value = -1;
        bool pretty_header = i.cond >= 0 && inlinable_region(i.regions[0], i.cond, -1, nullptr);
        bool pretty_update = i.for_var >= 0 && !i.regions[2].insts.empty() &&
                             inlinable_region(i.regions[2], -1, i.for_var, &update_value);

        cur_line_ = i.line;
        if (pretty_header && (i.regions[2].insts.empty() || pretty_update)) {
            // Header and update fold into expressions: emit `while` / `for`.
            ++depth_;
            region_values(i.regions[0]);
            std::string cond = operand(i.cond).text;
            std::string head;
            if (i.regions[2].insts.empty()) {
                head = "while " + cond + " {";
            } else {
                region_values(i.regions[2]);
                const std::string& n = names_.at(i.for_var);
                std::string v = operand(update_value).text;
                std::string upd = v == n + " + 1" ? n + "++" : n + " = " + v;
                head = "for (; " + cond + "; " + upd + ") {";
            }
            --depth_;
            cur_line_ = i.line;
            stmt(head);
            ++indent_;
            region(i.regions[1]);
            --indent_;
            cur_line_ = i.line;
            stmt("}");
            return;
        }

        stmt("loop {");
        ++indent_;
        ++depth_;   // header values stay visible to the body and continuing
        region_values(i.regions[0]);
        if (i.cond >= 0) {
            cur_line_ = i.line;
            Expr c = operand(i.cond);
            stmt("if !" + wrap(c, POSTFIX) + " { break; }");
        }
        region(i.regions[1]);
        if (!i.regions[2].insts.empty()) {
            cur_line_ = i.line;
            stmt("continuing {");
            ++indent_;
            region(i.regions[2]);
            --indent_;
            stmt("}");
        }
        for (auto it = pending_.begin(); it != pending_.end();)
            it = it->second.depth == depth_ ? pending_.erase(it) : std::next(it);
        --depth_;
        --indent_;
        cur_line_ = i.line;
        stmt("}");
    }

    // Define the values of an expression-only region (loop headers / updates).
    void region_values(const Region& r) {
        for (const auto& i : r.insts) {
            if (i.op == Op::Const || i.op == Op::Uniform) leafs_[i.id] = &i;
            else if (i.id >= 0) define(i, value(i));
        }
    }

    void function(const Function& f) {
        fn_ = &f;
        uses_ = use_counts(f);
        names_.clear();
        taken_.clear();
        pending_.clear();
        leafs_.clear();
        depth_ = 0;
        cur_line_ = f.line;

        std::vector<std::string> prologue;
        std::string sig;
        if (f.stage != Stage::None) {
            line(std::string("@") + stage_name(f.stage), f.line);
        }
        sig = "fn " + f.name + "(";
        std::unordered_map<int, int> arg_ids;
        for (const auto& i : f.body.insts) if (i.op == Op::Arg) arg_ids[i.imm] = i.id;
        for (size_t k = 0; k < f.param_types.size(); ++k) {
            std::string n = fresh_name(f.param_names[k]);
            if (arg_ids.count(static_cast<int>(k))) names_[arg_ids[static_cast<int>(k)]] = n;
            std::string attr, type = wgsl_type(f.param_types[k]);
            if (f.stage != Stage::None) {
                const EntryParam& ep = f.entry_params[k];
                if (!ep.builtin.empty()) {
                    attr = "@builtin(" + ep.builtin + ") ";
                    if (ep.builtin == "vertex_index" || ep.builtin == "instance_index") {
                        std::string raw = fresh_name(n + "_u32");
                        prologue.push_back("let " + n + " = i32(" + raw + ");");
                        sig += (k ? ", " : "") + attr + raw + ": u32";
                        continue;
                    }
                } else {
                    attr = "@location(" + std::to_string(ep.location) + ") ";
                }
            }
            sig += (k ? ", " : "") + attr + n + ": " + type;
        }
        sig += ")";
        if (!f.return_type.is_void()) {
            std::string ret_attr = f.stage == Stage::Fragment ? "@location(0) "
                                 : f.stage == Stage::Vertex   ? "@builtin(position) " : "";
            sig += " -> " + ret_attr + wgsl_type(f.return_type);
        }
        line(sig + " {", f.line);
        ++indent_;
        for (const auto& p : prologue) line(p, f.line);
        region(f.body);
        --indent_;
        line("}", f.line);
        fn_ = nullptr;
    }
};

} // namespace

WgslOutput emit_wgsl(const ir::Module& m) { return Emitter(m).run(); }

} // namespace backend
